### ISSUE TITLE
FML doesn't like urllib2

### ISSUE THREAD

**Issue by frozencemetery** [frozencemetery/lurker#26]
``` python
>>> import urllib2
>>> html = urllib2.urlopen("http://www.fmylife.com/random").read()
# trimmed
urllib2.HTTPError: HTTP Error 403: Forbidden
>>>
```

It fails to import on bot start (and at any other time, for that matter).

**Comment by frozencemetery** [comment]
(To finish the thought: it works fine under curl.)

**Comment by cstanfill** [comment]
Spoofing your user agent to "Mozilla/5.0 (X11; U; Linux i686) Gecko/20071127 Firefox/2.0.0.11" before making the request seems to get around this
